import useStore from '../../store/useStore'
import { NODE_TYPE_CONFIG, CONFIDENCE_LEVELS } from '../../config/nodeTypes'
import { EDGE_RELATIONSHIP_TYPES } from '../../config/edgeTypes'
import styles from './ReportModal.module.css'

export default function ReportModal({ onClose }) {
  const { nodes, edges, caseInfo } = useStore.getState()

  const generate = () => {
    const date = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })
    const nodesByType = {}
    nodes.forEach((n) => {
      const t = n.data.nodeType
      if (!nodesByType[t]) nodesByType[t] = []
      nodesByType[t].push(n)
    })

    const confColor = { confirmed: '#22c55e', probable: '#f59e0b', unverified: '#6b7280' }

    const nodeRows = nodes.map((n) => {
      const cfg = NODE_TYPE_CONFIG[n.data.nodeType] ?? {}
      const conf = CONFIDENCE_LEVELS[n.data.confidence ?? 'unverified']
      return `<tr>
        <td>${cfg.icon ?? ''} ${cfg.label ?? n.data.nodeType}</td>
        <td><strong>${escHtml(n.data.value)}</strong></td>
        <td style="color:${confColor[n.data.confidence ?? 'unverified']}">${conf?.label ?? ''}</td>
        <td>${escHtml(n.data.sourceUrl)}</td>
        <td>${escHtml(n.data.dateAdded)}</td>
        <td>${escHtml(n.data.tags)}</td>
        <td>${escHtml(n.data.note)}</td>
      </tr>`
    }).join('')

    const edgeRows = edges.map((e) => {
      const src = nodes.find((n) => n.id === e.source)
      const tgt = nodes.find((n) => n.id === e.target)
      const rel = EDGE_RELATIONSHIP_TYPES[e.data?.relationshipType ?? 'default']
      return `<tr>
        <td>${escHtml(src?.data.value || src?.data.label || e.source)}</td>
        <td style="color:${rel?.color ?? '#5a6290'}">${rel?.label ?? 'Link'}</td>
        <td>${escHtml(tgt?.data.value || tgt?.data.label || e.target)}</td>
        <td>${escHtml(e.data?.label)}</td>
      </tr>`
    }).join('')

    const images = nodes.filter((n) => n.data.nodeType === 'image' && n.data.imageUrl)
    const imgSection = images.length ? `
      <h2>Evidence Images</h2>
      <div style="display:flex;flex-wrap:wrap;gap:16px">
        ${images.map((n) => `<div>
          <img src="${n.data.imageUrl}" style="max-width:300px;max-height:200px;border-radius:6px;border:1px solid #333">
          <div style="font-size:11px;color:#999;margin-top:4px">${escHtml(n.data.value)}</div>
        </div>`).join('')}
      </div>` : ''

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>OSINT Report – ${escHtml(caseInfo.name)}</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; background: #0f1117; color: #e2e8f0; margin: 0; padding: 40px; }
  h1 { color: #7c8cf8; margin-bottom: 4px; }
  h2 { color: #c4cbf5; font-size: 15px; margin: 32px 0 10px; border-bottom: 1px solid #2d3148; padding-bottom: 6px; }
  .meta { display: flex; gap: 24px; font-size: 12px; color: #6b7280; margin-bottom: 32px; flex-wrap: wrap; }
  .meta span strong { color: #9ca3af; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th { background: #1e2235; color: #6b7280; font-size: 10px; text-transform: uppercase; letter-spacing: 0.8px; padding: 7px 10px; text-align: left; }
  td { padding: 7px 10px; border-bottom: 1px solid #1e2235; color: #c4cbf5; vertical-align: top; word-break: break-word; max-width: 200px; }
  tr:hover td { background: #1a1d2a; }
  .badge { display: inline-block; padding: 2px 7px; border-radius: 4px; font-size: 10px; font-weight: 600; }
  @media print { body { background: white; color: black; } th { background: #f0f0f0; color: #333; } td { color: #222; border-color: #ddd; } }
</style>
</head>
<body>
<h1>🔍 ${escHtml(caseInfo.name)}</h1>
<div class="meta">
  <span><strong>Investigator:</strong> ${escHtml(caseInfo.investigator) || '—'}</span>
  <span><strong>Status:</strong> ${escHtml(caseInfo.status)}</span>
  <span><strong>Generated:</strong> ${date}</span>
  <span><strong>Nodes:</strong> ${nodes.length}</span>
  <span><strong>Connections:</strong> ${edges.length}</span>
</div>
${caseInfo.description ? `<p style="color:#9ca3af;font-size:13px;margin-bottom:24px">${escHtml(caseInfo.description)}</p>` : ''}

<h2>Investigation Objective</h2>
<p style="color:#9ca3af;font-size:13px">${escHtml(caseInfo.description) || 'No description provided.'}</p>

<h2>Nodes (${nodes.length})</h2>
<table>
  <thead><tr><th>Type</th><th>Value</th><th>Confidence</th><th>Source</th><th>Date</th><th>Tags</th><th>Notes</th></tr></thead>
  <tbody>${nodeRows}</tbody>
</table>

<h2>Connections (${edges.length})</h2>
<table>
  <thead><tr><th>From</th><th>Relationship</th><th>To</th><th>Label</th></tr></thead>
  <tbody>${edgeRows}</tbody>
</table>

${imgSection}

<p style="margin-top:48px;font-size:10px;color:#4b5280;border-top:1px solid #1e2235;padding-top:16px">
  Generated by OSINT Canvas · ${new Date().toISOString()}
</p>
</body>
</html>`

    const blob = new Blob([html], { type: 'text/html' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `osint-report-${(caseInfo.name || 'case').replace(/\s+/g, '-').toLowerCase()}-${new Date().toISOString().slice(0, 10)}.html`
    a.click()
    URL.revokeObjectURL(a.href)
    onClose()
  }

  return (
    <div className={styles.overlay} onClick={onClose}>
      <div className={styles.modal} onClick={(e) => e.stopPropagation()}>
        <div className={styles.header}>
          <span>📄 Generate Report</span>
          <button className={styles.closeBtn} onClick={onClose}>✕</button>
        </div>
        <div className={styles.body}>
          <p>Generates a self-contained <strong>HTML report</strong> with:</p>
          <ul>
            <li>Case metadata (name, investigator, status, objective)</li>
            <li>All {nodes.length} nodes with confidence, source, date, tags and notes</li>
            <li>All {edges.length} connections with relationship types</li>
            <li>Embedded evidence images</li>
          </ul>
          <p className={styles.note}>The file can be printed to PDF from any browser.</p>
        </div>
        <div className={styles.footer}>
          <button className={styles.cancelBtn} onClick={onClose}>Cancel</button>
          <button className={styles.generateBtn} onClick={generate}>Generate & Download</button>
        </div>
      </div>
    </div>
  )
}

function escHtml(str) {
  return String(str ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}
