export const ENGINES = [
  { name: 'Google',     url: 'https://www.google.com/search?q=' },
  { name: 'Bing',       url: 'https://www.bing.com/search?q=' },
  { name: 'DuckDuckGo', url: 'https://duckduckgo.com/?q=' },
  { name: 'Yandex',     url: 'https://yandex.com/search/?text=' },
]

const q = (tpl) => ({ query: tpl, engine: null })
const custom = (tpl, engine) => ({ query: tpl, engine })

// Each template: { label, query: (value) => string, engine: null | { name, url } }
export const DORK_TEMPLATES = {
  person: [
    { label: 'General search',       ...q((v) => `"${v}"`) },
    { label: 'LinkedIn profile',      ...q((v) => `"${v}" site:linkedin.com`) },
    { label: 'Email address',         ...q((v) => `"${v}" email OR "@"`) },
    { label: 'Phone number',          ...q((v) => `"${v}" phone OR tel OR mobile`) },
    { label: 'PDF / Word documents',  ...q((v) => `"${v}" filetype:pdf OR filetype:docx`) },
    { label: 'Social media',          ...q((v) => `"${v}" site:twitter.com OR site:instagram.com OR site:facebook.com`) },
    { label: 'Pastebin leaks',        ...q((v) => `"${v}" site:pastebin.com`) },
    { label: 'Court / legal records', ...q((v) => `"${v}" lawsuit OR court OR legal OR settlement`) },
    { label: 'News mentions',         ...q((v) => `"${v}" news`) },
  ],
  alias: [
    { label: 'General search',  ...q((v) => `"${v}"`) },
    { label: 'GitHub',          ...q((v) => `"${v}" site:github.com`) },
    { label: 'Reddit',          ...q((v) => `"${v}" site:reddit.com`) },
    { label: 'Twitter / X',     ...q((v) => `"${v}" site:twitter.com OR site:x.com`) },
    { label: 'Gaming / Discord',...q((v) => `"${v}" site:steamcommunity.com OR site:twitch.tv OR site:discord.com`) },
    { label: 'Forum posts',     ...q((v) => `"${v}" inurl:forum OR inurl:thread OR inurl:profile`) },
    { label: 'Pastebin',        ...q((v) => `"${v}" site:pastebin.com`) },
    { label: 'Image boards',    ...q((v) => `"${v}" site:4chan.org OR site:8kun.top`) },
  ],
  email: [
    { label: 'General search',      ...q((v) => `"${v}"`) },
    { label: 'Excluding own domain',...q((v) => `"${v}" -site:${v.split('@')[1] ?? 'example.com'}`) },
    { label: 'Password leaks',      ...q((v) => `"${v}" password OR passwd`) },
    { label: 'Pastebin leaks',      ...q((v) => `"${v}" site:pastebin.com`) },
    { label: 'LinkedIn',            ...q((v) => `"${v}" site:linkedin.com`) },
    { label: 'GitHub commits',      ...q((v) => `"${v}" site:github.com`) },
    { label: 'Social accounts',     ...q((v) => `"${v}" site:twitter.com OR site:facebook.com OR site:instagram.com`) },
    { label: 'HaveIBeenPwned',      ...custom((v) => v, { name: 'HIBP', url: 'https://haveibeenpwned.com/account/' }) },
    { label: 'Epieos lookup',       ...custom((v) => v, { name: 'Epieos', url: 'https://epieos.com/?q=' }) },
  ],
  phone: [
    { label: 'General search',   ...q((v) => `"${v}"`) },
    { label: 'Social mentions',  ...q((v) => `"${v}" site:facebook.com OR site:twitter.com`) },
    { label: 'Business listing', ...q((v) => `"${v}" company OR business OR contact`) },
    { label: 'Scam reports',     ...q((v) => `"${v}" scam OR fraud OR spam OR complaint`) },
    { label: 'Linked to email',  ...q((v) => `"${v}" email OR "@"`) },
    { label: 'TrueCaller',       ...custom((v) => v.replace(/\D/g,''), { name: 'TrueCaller', url: 'https://www.truecaller.com/search/nl/' }) },
  ],
  ip: [
    { label: 'General search',       ...q((v) => `"${v}"`) },
    { label: 'Open ports / banners', ...q((v) => `"${v}" port OR banner OR service`) },
    { label: 'Pastebin mentions',    ...q((v) => `"${v}" site:pastebin.com`) },
    { label: 'Abuse reports',        ...q((v) => `"${v}" abuse OR spam OR malicious`) },
    { label: 'Shodan',               ...custom((v) => v, { name: 'Shodan', url: 'https://www.shodan.io/search?query=' }) },
    { label: 'AbuseIPDB',            ...custom((v) => v, { name: 'AbuseIPDB', url: 'https://www.abuseipdb.com/check/' }) },
    { label: 'VirusTotal',           ...custom((v) => v, { name: 'VirusTotal', url: 'https://www.virustotal.com/gui/ip-address/' }) },
    { label: 'Greynoise',            ...custom((v) => v, { name: 'GreyNoise', url: 'https://viz.greynoise.io/ip/' }) },
  ],
  url: [
    { label: 'Site index',           ...q((v) => `site:${v.replace(/https?:\/\//,'').split('/')[0]}`) },
    { label: 'Admin / login pages',  ...q((v) => `site:${v.replace(/https?:\/\//,'').split('/')[0]} inurl:admin OR inurl:login OR inurl:dashboard OR inurl:wp-admin`) },
    { label: 'Exposed files',        ...q((v) => `site:${v.replace(/https?:\/\//,'').split('/')[0]} filetype:pdf OR filetype:xls OR filetype:sql OR filetype:env`) },
    { label: 'Config / backup files',...q((v) => `site:${v.replace(/https?:\/\//,'').split('/')[0]} inurl:config OR inurl:backup OR inurl:.git`) },
    { label: 'External mentions',    ...q((v) => `"${v.replace(/https?:\/\//,'').split('/')[0]}" -site:${v.replace(/https?:\/\//,'').split('/')[0]}`) },
    { label: 'Tech stack clues',     ...q((v) => `site:${v.replace(/https?:\/\//,'').split('/')[0]} "powered by" OR "built with"`) },
    { label: 'Subdomains (crt.sh)',  ...custom((v) => v.replace(/https?:\/\//,'').split('/')[0], { name: 'crt.sh', url: 'https://crt.sh/?q=%25.' }) },
    { label: 'Wayback Machine',      ...custom((v) => v, { name: 'Wayback', url: 'https://web.archive.org/web/*/' }) },
    { label: 'URLScan',              ...custom((v) => v.replace(/https?:\/\//,'').split('/')[0], { name: 'URLScan', url: 'https://urlscan.io/search/#domain:' }) },
  ],
  organization: [
    { label: 'General search',       ...q((v) => `"${v}"`) },
    { label: 'LinkedIn employees',   ...q((v) => `"${v}" site:linkedin.com/in`) },
    { label: 'Job postings',         ...q((v) => `"${v}" site:linkedin.com/jobs OR site:indeed.com`) },
    { label: 'Exposed documents',    ...q((v) => `"${v}" filetype:pdf OR filetype:pptx OR filetype:xlsx`) },
    { label: 'Email format',         ...q((v) => `"${v}" "@" employees email format`) },
    { label: 'News coverage',        ...q((v) => `"${v}" site:reuters.com OR site:bloomberg.com OR site:techcrunch.com`) },
    { label: 'Data breach mentions', ...q((v) => `"${v}" breach OR leak OR hacked OR exposed`) },
    { label: 'Court / legal',        ...q((v) => `"${v}" lawsuit OR legal OR settlement OR court`) },
    { label: 'Subsidiaries',         ...q((v) => `"${v}" subsidiary OR "owned by" OR "division of"`) },
  ],
  crypto: [
    { label: 'Wallet mentions', ...q((v) => `"${v}"`) },
    { label: 'Scam reports',    ...q((v) => `"${v}" scam OR fraud OR stolen OR ransom`) },
    { label: 'Forum mentions',  ...q((v) => `"${v}" site:bitcointalk.org OR site:reddit.com`) },
    { label: 'Blockchain.com',  ...custom((v) => v, { name: 'Blockchain', url: 'https://www.blockchain.com/explorer/search?search=' }) },
    { label: 'Etherscan',       ...custom((v) => v, { name: 'Etherscan', url: 'https://etherscan.io/search?q=' }) },
    { label: 'Breadcrumbs',     ...custom((v) => v, { name: 'Breadcrumbs', url: 'https://www.breadcrumbs.app/reports/' }) },
  ],
  address: [
    { label: 'General search',  ...q((v) => `"${v}"`) },
    { label: 'Business at addr',...q((v) => `"${v}" company OR business OR registered`) },
    { label: 'Property records',...q((v) => `"${v}" property OR owner OR deed OR cadastral`) },
    { label: 'People search',   ...q((v) => `"${v}" resident OR occupant OR owner`) },
    { label: 'Google Maps',     ...custom((v) => encodeURIComponent(v), { name: 'Maps', url: 'https://maps.google.com/?q=' }) },
  ],
  vehicle: [
    { label: 'General search',    ...q((v) => `"${v}"`) },
    { label: 'License plate',     ...q((v) => `"${v}" plate OR registration OR vehicle`) },
    { label: 'Stolen vehicle',    ...q((v) => `"${v}" stolen OR report`) },
    { label: 'Accident reports',  ...q((v) => `"${v}" accident OR incident OR collision`) },
  ],
  default: [
    { label: 'General search', ...q((v) => `"${v}"`) },
    { label: 'Pastebin',       ...q((v) => `"${v}" site:pastebin.com`) },
    { label: 'Documents',      ...q((v) => `"${v}" filetype:pdf OR filetype:docx`) },
    { label: 'News',           ...q((v) => `"${v}" news`) },
  ],
}

export const DORK_OPERATORS = [
  { op: 'site:',     hint: 'Limit to domain',        placeholder: 'site:example.com' },
  { op: 'filetype:', hint: 'Specific file type',      placeholder: 'filetype:pdf' },
  { op: 'inurl:',    hint: 'Keyword in URL',          placeholder: 'inurl:admin' },
  { op: 'intitle:',  hint: 'Keyword in page title',   placeholder: 'intitle:"index of"' },
  { op: 'intext:',   hint: 'Keyword in body',         placeholder: 'intext:password' },
  { op: 'before:',   hint: 'Published before date',   placeholder: 'before:2023-01-01' },
  { op: 'after:',    hint: 'Published after date',    placeholder: 'after:2020-01-01' },
  { op: '-',         hint: 'Exclude term',            placeholder: '-site:example.com' },
  { op: 'OR',        hint: 'Either term',             placeholder: 'term1 OR term2' },
  { op: 'cache:',    hint: 'Cached version of page',  placeholder: 'cache:example.com' },
  { op: '"..."',     hint: 'Exact phrase',            placeholder: '"exact phrase"' },
]
