export const EDGE_RELATIONSHIP_TYPES = {
  // General
  default:       { label: 'linked to',         color: '#6b7280', dash: false, group: 'General',       bidirectional: false },
  suspected:     { label: 'suspected link',     color: '#94a3b8', dash: true,  group: 'General',       bidirectional: false },

  // Identity
  alias_of:      { label: 'alias of',           color: '#a78bfa', dash: false, group: 'Identity',      bidirectional: false },
  owns:          { label: 'owns',               color: '#60a5fa', dash: false, group: 'Identity',      bidirectional: false },
  member_of:     { label: 'member of',          color: '#818cf8', dash: false, group: 'Identity',      bidirectional: false },
  impersonates:  { label: 'impersonates',       color: '#f472b6', dash: true,  group: 'Identity',      bidirectional: false },

  // Communication
  communicated:  { label: 'communicated with',  color: '#34d399', dash: false, group: 'Communication', bidirectional: true  },
  contacted:     { label: 'contacted',          color: '#34d399', dash: true,  group: 'Communication', bidirectional: false },

  // Technical
  resolves_to:   { label: 'resolves to',        color: '#fbbf24', dash: false, group: 'Technical',     bidirectional: false },
  hosted_on:     { label: 'hosted on',          color: '#fbbf24', dash: true,  group: 'Technical',     bidirectional: false },
  registered:    { label: 'registered',         color: '#fb923c', dash: false, group: 'Technical',     bidirectional: false },

  // Location
  located_at:    { label: 'located at',         color: '#f472b6', dash: false, group: 'Location',      bidirectional: false },
  visited:       { label: 'visited',            color: '#f472b6', dash: true,  group: 'Location',      bidirectional: false },

  // Evidence
  evidence_of:   { label: 'evidence of',        color: '#f87171', dash: false, group: 'Evidence',      bidirectional: false },
  references:    { label: 'references',         color: '#f87171', dash: true,  group: 'Evidence',      bidirectional: false },
}

// Confidence levels for edges
export const EDGE_CONFIDENCE = {
  unverified: { label: 'Unverified', color: '#4b5563', strokeWidth: 1.2, opacity: 0.45 },
  suspected:  { label: 'Suspected',  color: null,      strokeWidth: 1.5, opacity: 0.65 },
  probable:   { label: 'Probable',   color: null,      strokeWidth: 2.0, opacity: 0.85 },
  confirmed:  { label: 'Confirmed',  color: null,      strokeWidth: 3.0, opacity: 1.0  },
}

// Infer a default relationship type from connected node types
export function inferRelationship(sourceType, targetType) {
  const map = {
    // Person
    'person→email':           'owns',
    'person→phone':           'owns',
    'person→social':          'owns',
    'person→address':         'located_at',
    'person→ip':              'registered',
    'person→url':             'owns',
    'person→crypto':          'owns',
    'person→vehicle':         'owns',
    'person→organization':    'member_of',
    'person→person':          'communicated',
    'person→alias':           'alias_of',
    'person→location':        'located_at',
    'person→username':        'owns',
    'person→government_id':   'owns',
    'person→sim_card':        'owns',
    'person→chat_account':    'owns',
    'person→forum_account':   'owns',
    'person→domain':          'registered',
    'person→network_device':  'owns',
    'person→imei':            'owns',
    'person→darkweb':         'owns',
    'person→company':         'member_of',
    'person→bank_account':    'owns',
    'person→transaction':     'evidence_of',
    'person→coordinates':     'located_at',
    'person→facility':        'located_at',
    // Alias / username
    'alias→person':           'alias_of',
    'username→person':        'alias_of',
    'username→social':        'owns',
    'username→forum_account': 'alias_of',
    // Contact / identity
    'email→person':           'owns',
    'phone→person':           'owns',
    'social→person':          'owns',
    'government_id→person':   'owns',
    'sim_card→phone':         'owns',
    'sim_card→person':        'owns',
    'sim_card→imei':          'owns',
    'imei→phone':             'owns',
    'imei→person':            'owns',
    'chat_account→person':    'owns',
    'chat_account→chat_account': 'communicated',
    'forum_account→person':   'owns',
    // Online / technical
    'ip→url':                 'hosted_on',
    'ip→domain':              'resolves_to',
    'ip→network_device':      'owns',
    'url→ip':                 'hosted_on',
    'url→domain':             'hosted_on',
    'domain→ip':              'resolves_to',
    'domain→certificate':     'owns',
    'domain→organization':    'registered',
    'domain→company':         'registered',
    'domain→url':             'hosted_on',
    'certificate→domain':     'owns',
    'certificate→organization':'owns',
    'certificate→company':    'owns',
    'network_device→ip':      'owns',
    'network_device→person':  'owns',
    'network_device→domain':  'resolves_to',
    'darkweb→person':         'evidence_of',
    'darkweb→organization':   'evidence_of',
    'darkweb→ip':             'hosted_on',
    'darkweb→malware':        'evidence_of',
    'file_hash→malware':      'evidence_of',
    'file_hash→person':       'evidence_of',
    'malware→person':         'evidence_of',
    'malware→organization':   'evidence_of',
    'malware→ip':             'hosted_on',
    'malware→domain':         'hosted_on',
    // Financial
    'company→person':         'member_of',
    'company→address':        'located_at',
    'company→location':       'located_at',
    'company→facility':       'located_at',
    'company→bank_account':   'owns',
    'company→domain':         'registered',
    'company→crypto':         'owns',
    'bank_account→person':    'owns',
    'bank_account→company':   'owns',
    'bank_account→transaction':'evidence_of',
    'transaction→bank_account':'evidence_of',
    'transaction→person':     'evidence_of',
    'transaction→company':    'evidence_of',
    'transaction→crypto':     'evidence_of',
    // Physical
    'coordinates→location':   'located_at',
    'coordinates→facility':   'located_at',
    'coordinates→person':     'evidence_of',
    'facility→location':      'located_at',
    'facility→organization':  'owns',
    'facility→company':       'owns',
    'organization→person':    'member_of',
    'organization→address':   'located_at',
    'organization→location':  'located_at',
    'organization→facility':  'owns',
    'organization→domain':    'registered',
    // Evidence
    'image→person':           'evidence_of',
    'image→event':            'evidence_of',
    'image→coordinates':      'evidence_of',
    'document→person':        'evidence_of',
    'document→event':         'evidence_of',
    'document→organization':  'evidence_of',
    'document→file_hash':     'evidence_of',
    'leaked_data→person':     'evidence_of',
    'leaked_data→email':      'evidence_of',
    'leaked_data→phone':      'evidence_of',
    'leaked_data→bank_account':'evidence_of',
    'screenshot→person':      'evidence_of',
    'screenshot→url':         'evidence_of',
    'screenshot→chat_account':'evidence_of',
    'warrant→person':         'evidence_of',
    'warrant→company':        'evidence_of',
    'warrant→organization':   'evidence_of',
    // Intelligence
    'source→person':          'evidence_of',
    'source→event':           'evidence_of',
    'source→document':        'evidence_of',
    'keyword→url':            'evidence_of',
    'keyword→domain':         'evidence_of',
    // Target
    'target→person':          'alias_of',
    'target→organization':    'member_of',
    'target→company':         'owns',
  }
  return map[`${sourceType}→${targetType}`] ?? 'default'
}

export const EDGE_REL_GROUPS = ['General', 'Identity', 'Communication', 'Technical', 'Location', 'Evidence']

// Returns ordered list of suggested relationship keys for a node pair, or null (show all)
export function suggestedRelationships(sourceType, targetType) {
  const map = {
    // Person
    'person→email':             ['owns', 'contacted', 'communicated'],
    'person→phone':             ['owns', 'contacted', 'communicated'],
    'person→social':            ['owns', 'alias_of', 'impersonates'],
    'person→ip':                ['registered', 'hosted_on'],
    'person→url':               ['owns', 'registered', 'visited'],
    'person→address':           ['located_at', 'visited'],
    'person→location':          ['located_at', 'visited'],
    'person→coordinates':       ['located_at', 'visited'],
    'person→organization':      ['member_of', 'owns'],
    'person→company':           ['member_of', 'owns'],
    'person→person':            ['communicated', 'contacted', 'alias_of', 'member_of'],
    'person→alias':             ['alias_of', 'impersonates'],
    'person→username':          ['owns', 'alias_of'],
    'person→vehicle':           ['owns'],
    'person→crypto':            ['owns'],
    'person→bank_account':      ['owns'],
    'person→sim_card':          ['owns'],
    'person→imei':              ['owns'],
    'person→chat_account':      ['owns'],
    'person→forum_account':     ['owns'],
    'person→government_id':     ['owns'],
    'person→document':          ['references', 'evidence_of'],
    'person→event':             ['communicated', 'located_at'],
    'person→darkweb':           ['owns', 'visited'],
    'person→domain':            ['registered', 'owns'],
    'person→network_device':    ['owns'],
    'person→facility':          ['located_at', 'visited'],
    // Identity
    'alias→person':             ['alias_of', 'impersonates'],
    'username→person':          ['alias_of', 'owns'],
    'username→social':          ['owns', 'alias_of'],
    'government_id→person':     ['owns'],
    // Contact
    'social→person':            ['owns', 'alias_of'],
    'email→person':             ['owns'],
    'phone→person':             ['owns', 'contacted'],
    'sim_card→phone':           ['owns'],
    'sim_card→person':          ['owns'],
    'sim_card→imei':            ['owns'],
    'imei→phone':               ['owns'],
    'imei→person':              ['owns'],
    'chat_account→person':      ['owns'],
    'chat_account→chat_account':['communicated', 'contacted'],
    'forum_account→person':     ['owns'],
    // Online / technical
    'ip→url':                   ['hosted_on', 'resolves_to'],
    'ip→domain':                ['resolves_to', 'hosted_on'],
    'ip→network_device':        ['owns'],
    'url→ip':                   ['hosted_on'],
    'url→domain':               ['hosted_on'],
    'domain→ip':                ['resolves_to'],
    'domain→certificate':       ['owns'],
    'domain→company':           ['registered'],
    'domain→organization':      ['registered'],
    'certificate→domain':       ['owns'],
    'network_device→ip':        ['owns'],
    'darkweb→ip':               ['hosted_on'],
    'darkweb→malware':          ['evidence_of'],
    'file_hash→malware':        ['evidence_of'],
    'malware→ip':               ['hosted_on'],
    'malware→domain':           ['hosted_on'],
    // Financial
    'company→person':           ['member_of'],
    'company→bank_account':     ['owns'],
    'company→domain':           ['registered'],
    'company→facility':         ['located_at'],
    'bank_account→person':      ['owns'],
    'bank_account→company':     ['owns'],
    'bank_account→transaction': ['evidence_of'],
    'transaction→bank_account': ['evidence_of'],
    'transaction→person':       ['evidence_of'],
    'transaction→crypto':       ['evidence_of'],
    // Physical
    'facility→location':        ['located_at'],
    'facility→company':         ['owns'],
    'organization→person':      ['member_of'],
    'organization→address':     ['located_at'],
    'organization→location':    ['located_at'],
    'organization→ip':          ['registered', 'hosted_on'],
    'coordinates→location':     ['located_at'],
    'coordinates→facility':     ['located_at'],
    // Evidence
    'image→person':             ['evidence_of', 'references'],
    'image→event':              ['evidence_of'],
    'image→location':           ['evidence_of'],
    'image→coordinates':        ['evidence_of'],
    'document→person':          ['evidence_of', 'references'],
    'document→event':           ['evidence_of'],
    'document→organization':    ['evidence_of', 'references'],
    'document→file_hash':       ['evidence_of'],
    'screenshot→url':           ['evidence_of'],
    'screenshot→person':        ['evidence_of'],
    'leaked_data→person':       ['evidence_of'],
    'leaked_data→email':        ['evidence_of'],
    'leaked_data→phone':        ['evidence_of'],
    'leaked_data→bank_account': ['evidence_of'],
    'warrant→person':           ['evidence_of'],
    'warrant→company':          ['evidence_of'],
    // Legacy
    'crypto→person':            ['owns'],
    'vehicle→person':           ['owns'],
    'target→person':            ['alias_of', 'communicated'],
    'target→organization':      ['member_of'],
    'source→person':            ['evidence_of'],
    'source→event':             ['evidence_of'],
  }
  return map[`${sourceType}→${targetType}`] ?? null
}
