export const METHOD_TECHNIQUES = {
  password_reset:   { label: 'Password Reset',        icon: '🔑', desc: 'Triggered a password reset to reveal partial phone / email' },
  breach_search:    { label: 'Breach / Leak Search',  icon: '💧', desc: 'Searched breach databases (HIBP, Snusbase, etc.)' },
  whois:            { label: 'WHOIS / Domain Lookup', icon: '🌐', desc: 'Queried WHOIS, DNS, or domain registration records' },
  reverse_phone:    { label: 'Reverse Phone Lookup',  icon: '📞', desc: 'Reverse-searched a phone number (Truecaller, NumLookup, etc.)' },
  reverse_image:    { label: 'Reverse Image Search',  icon: '🖼', desc: 'Reverse image searched (Google Lens, TinEye, Yandex)' },
  username_search:  { label: 'Username Search',       icon: '🔎', desc: 'Cross-platform username search (Sherlock, WhatsMyName, etc.)' },
  social_search:    { label: 'Social Media Search',   icon: '📱', desc: 'Searched / scraped a social media platform' },
  google_dork:      { label: 'Google Dork',           icon: '🎯', desc: 'Used search operator queries to surface hidden data' },
  email_verify:     { label: 'Email Verification',    icon: '📧', desc: 'Verified email validity or linked accounts' },
  port_scan:        { label: 'Port / Host Scan',      icon: '🖥', desc: 'Scanned open ports or services (Shodan, nmap, etc.)' },
  phone_lookup:     { label: 'Phone Number Lookup',   icon: '📟', desc: 'Looked up carrier, location, or owner of a phone number' },
  address_lookup:   { label: 'Address Lookup',        icon: '📍', desc: 'Searched property or address records' },
  court_records:    { label: 'Court / Public Records',icon: '🏛', desc: 'Searched court filings, business registrations, or public records' },
  darkweb_search:   { label: 'Dark Web Search',       icon: '🕶', desc: 'Searched dark web forums or marketplaces' },
  ip_lookup:        { label: 'IP / Geo Lookup',       icon: '🗺', desc: 'Geolocated or reverse-traced an IP address' },
  account_recovery: { label: 'Account Recovery',      icon: '🔓', desc: 'Used account recovery flow to surface linked identifiers' },
  manual:           { label: 'Manual Research',       icon: '🖊', desc: 'Direct manual investigation / open-source research' },
  other:            { label: 'Other Technique',       icon: '⚡', desc: 'Custom or unlisted technique' },
}
